<section>
<h1>Positionen</h1>
<h2>Jugendgewalt</h2>
<p>Der Jugendgewalt muss mit Null-Toleranz begegnet werden. Kriminelle Handlungen sind nicht zu tolerieren und müssen mit H&auml;rte bestraft werden. Kriminelle Aktionen Jugendlicher müssen mit Arbeitseins&auml;tzen bestraft werden. Bei minderj&auml;hrigen T&auml;tern müssen die Eltern in die Verantwortung gezogen werden. Nicht der Staat ist für die Erziehung verantwortlich, sondern die Eltern. Es muss begonnen werden, nicht die T&auml;ter, sondern die Opfer sowie m&ouml;gliche Opfer zu schützen.</p>
<h2>Finanzen</h2>
<p>Die Finanzen des Bundes sind in den Griff zu bekommen. Die Schulden, welche sich anh&auml;ufen und angeh&auml;uft haben, sind die Schulden unserer und der nachfolgenden Generation. Die Schulden von heute sind Steuern von morgen. Der zu hohe Schuldenberg darf nicht einfach so an uns Jungen übergeben werden. Es muss jetzt gehandelt werden. Die Schulden h&auml;ufen sich an, und dies trotz Schuldenbremse. Die Ausgaben müssen wie in jedem geregelten Haushalt den Einnahmen angepasst werden. So wie die Bürger den Gürtel enger schnallen mussten, muss dies nun auch der Staat tun.</p>
<h2>Steuern und Geb<? echo chr(252);?>hren</h2>
<p>Der Bürger muss mehr als ein halbes Jahr für Steuern, Abgaben, Pr&auml;mien und Gebühren arbeiten. Dies nur, weil der Staat nicht die Ausgaben den Einnahmen angepasst hat, sondern umgekehrt. Das darf nicht sein. Dem Bürger muss mehr erarbeitetes Geld im eigenen Sack bleiben. Er muss über seine Verdienste zum gr&ouml;ssten Teil selber bestimmen k&ouml;nnen und nicht über die H&auml;lfte jedes verdienten Franken in den Sozialluxus des Staats investieren müssen. Das Wirtschaftswachstum kann nur durch weniger Steuern und Abgaben gef&ouml;rdert werden, da dadurch das Volk mehr Geld für Investitionen hat.</p>
<h2>Sozialpolitik</h2>
<p>Die Schweiz hat sehr gute Sozialwerke. Wir müssen bestrebt sein, diese aufrecht zu halten. Dies bedeutet, der Missbrauch muss gestoppt werden. Wer das Anrecht hat, Sozialwerke zu beanspruchen, muss diese M&ouml;glichkeit haben. Wir müssen verhindern, dass die Sozialwerke ausgenützt werden k&ouml;nnen, von solchen, welche kein Anrecht darauf haben. Es muss darauf Wert gelegt werden, dass auch für unsere Generation sowie für die zukünftigen Generationen Sozialwerke bestehen. Die Zinsen der überschüssigen Goldreserven des Bundes müssen in die Sozialwerke investiert werden. Die Gleichberechtigung zwischen Mann und Frau muss auch bei der Rente eingeführt werden. Dies bedeutet Rentenalter für beide ab 65 Jahren.</p>
<h2>Bildungspolitik</h2>
<p>Das Bildungsniveau an den Volksschulen ist extrem gesunken. Dies ist eine Folge davon, dass die Durchmischung verschiedener Sprachen und Kulturen zu gross ist. An mehreren Schulen ist es üblich, dass über 50% der Schüler nicht Schweizerdeutsch sprechen k&ouml;nnen. So lernen die Kinder, auch die Schweizer Kinder, nicht einmal richtig Schweizerdeutsch, sondern direkt Schriftdeutsch. Im weiteren wird verlangt, dass auch noch Franz&ouml;sisch und Englisch gelernt wird. Wo bleiben da die Mathematik und Naturwissenschaft, welche die Basis für logische Überlegungen bilden. Diese F&auml;cher müssen wieder an Wichtigkeit gewinnen. Der gr&ouml;sste Teil der Bildungskosten wird für Stütz- und Sonderschulen ausgegeben. Die Hochbegabten, die Elite der sp&auml;teren Wissenschaft und Wirtschaft, werden links liegengelassen, anstatt gefordert und gef&ouml;rdert zu werden. Die Disziplin, der Fleiss und die Leistung müssen beurteilt und gef&ouml;rdert werden.</p>
<h2>Ausl&auml;nderpolitik</h2>
<p>Die Schweiz hat immer mehr Ausl&auml;nder, welche aus anderen Kulturen kommen. Die Schweiz muss darauf achten, dass die eigenen Gebr&auml;uche und Sitten aufrecht erhalten bleiben. Die Ausl&auml;nder müssen sich der Schweiz anpassen und nicht umgekehrt. Viele Ausl&auml;nder haben eine wichtige Funktion in der Arbeitswelt und verstossen nicht gegen Sitte und Gesetz. Ausl&auml;nder, welche die Rechte der Schweiz nicht akzeptieren und nicht befolgen, sind auszuweisen. Wer sich nicht anpassen will, oder die Systeme der Schweiz ausnutzen will, muss unser Land sofort verlassen. Die Einbürgerung soll als Belohnung der abgeschlossenen Integration gesehen werden. Sie darf nicht zu einem Mittel der Integration verkommen. Das Besitzen des Schweizer Passes muss als Ehre angesehen werden. Über die Einbürgerungen haben das Volk oder das Gemeindeparlament abschliessend zu entscheiden. Dieser Entscheid ist zu akzeptieren und soll nicht rekursf&auml;hig sein.</p>
<h2>EU-Politik</h2>
<p>Der Beitritt zur EU darf für die Schweiz keine Option sein. Die Grundwerte der Schweiz würden durch einen Beitritt aufgegeben werden. Die direkte Demokratie ist nach einem EU Beitritt nicht mehr m&ouml;glich. Abgeordnete in Brüssel würden über die Schweiz entscheiden und nicht mehr das Volk. Die Schweizer Vertreter in Brüssel h&auml;tten nur geringe Mitsprachem&ouml;glichkeit, dies, obwohl die Schweiz grosse Summen als Nettozahler leisten müsste. Die Souver&auml;nit&auml;t der Schweiz würde gef&auml;hrdet werden, sowie ihre Neutralit&auml;t. Weitere Nachteile w&auml;ren, dass die Mehrwertsteuer auf mindestens 15% ansteigen müsste, das Schweizer Steuersystem nicht akzeptiert würde und das Lohnniveau und damit der Wohlstand sinken würden.</p>
</section>
